version: '3.9'

services:
  mysql-database:
    container_name: "api-node-investments-manager-${ENV}-container"
    image: mysql:8.0.27
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "investments-database"
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./tmp/testDatabase:/var/lib/mysql
