version: '3.9'

name: "api-node-investments-manager-test"
services:
  mysql-database:
    image: mysql:8.0.27
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "investments-database"
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./tmp/${ENV}Database:/var/lib/mysql
